# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for project
  pod 'Reveal-SDK', :configurations => ['Debug']

  target 'projectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'projectUITests' do
    # Pods for testing
  end

end
